package io.sinzak.android.enums

enum class Page {
    HOME,
    HOME_MORE,
    HOME_NOTIFICATION,
    MARKET,
    OUTSOURCING,
    CHAT,
    PROFILE,
    PROFILE_SALE,
    PROFILE_WORK,
    PROFILE_EDIT,
    PROFILE_SETTING,
    PROFILE_CERTIFICATION,
    PROFILE_WEBMAIL,
    PROFILE_VERIFY,
    PROFILE_REPORT_TYPE,
    PROFILE_REPORT_SEND,
    PROFILE_SCRAP,
    PROFILE_REQUEST,

    NEW_POST,
    NEW_POST_IMAGE,
    NEW_POST_INFO,
    NEW_POST_SPEC,

    ART_DETAIL,
    ART_DETAIL_SUGGEST,

}